---
title: "Catalogue of the Art Exhibit at the Metropolitan Fair"
author: "Leanne Fortney"
date: "March 21, 2017"
output: html_document
---
```{r echo=FALSE} 

library(tidyverse)
library(ggraph)
library(ggplot2)
library(dplyr)
library(gapminder)
```
----
#1863 Worlds Metroplitan Fair 
---

```{r echo=FALSE} 
catalogue <- read_csv("~/Desktop/School/Clio2/Catalogue/Metropolitan_Fair.csv", 
  col_types =  cols(
  Date=col_integer(),
  Painting_num=col_integer(),
  School_Subject=col_character(), 
  Artist=col_character(), 
  Artist_School=col_character(), 
  Purchaser=col_character(),
  Price=col_integer()
))
```
```{r}  
catalogue %>%
  group_by(Artist, Artist_School) %>% 
      summarise(avg = mean(Price))
ggplot(catalogue, aes(x=Artist_School, y=Price))  +
  geom_boxplot(fill="#9476AB", color="black") +
   labs(title = "Range of Artist Sales Price per Artist School",
       x = "Artist School",
       y = "Price")
```
```{r, include=TRUE}  
catalogue %>% 
select(Artist_School, Artist, Price) %>% 
  filter(Artist_School == "English") 
ggplot(data = catalogue) + 
  geom_point(mapping = aes(x=Price, y=Artist, color=Artist_School)) +
       labs(title = "Art Work Price per Artist",
       x = "Price",
       y = "Artist",
       color = "Artist School")
```